### ISSUE TITLE
Determine output format of the pipeline

### ISSUE THREAD

**Issue by berleon** [BioroboticsLab/deeppipeline#1]
The current pipeline uses plain CSV as output format. A large collection of CSV files is the result.
(Is it right that there are over 1TB of CSV files?)
They are then processed and inserted into a PostgreSQL Database. 
The PostgreSQL database is currently used by the `bb_analysis`/ tracking project to get the output of the pipeline and to store ground truth data. 

The PostgreSQL database will be a traffic bottleneck for any map-reduce (spark) analysis. Also, it is quite big and needs a lot of storage. It would be preferable to have a storage format that is usable
for anyone.

My alternative proposal for the output format is [capnproto](https://capnproto.org/) or another fast serialization format. I suppose the capnproto format should use at least around 5 times less storage then the CSV files, mostly because they use binary encoding. If we apply some compression then even more. The new format would allow us to store the results on any PC. 

The schema would be something along this lines. 

```capnproto
struct Detection {
  id @0: UInt64;
  localizer_id @0: UInt64,    # the same for all detection based on the same localizer location
  x @0: UInt16;
  y @0: UInt16;
  rotation_z @ : Float32;
  rotation_y @ : Float32;
  rotation_x @ : Float32;
  radius @ : Float32;
  decoded_tag @: Float32;
  track_ids: List(UInt64);
  [Addition data e.g. autoencoder...]
}

# Corresponds to an image in the video
struct Frame {
  id @0: UInt64;
  cam @2: Text;
  world_coordinates_transform @3: List(Float);
  detection: @6: List(Detection);
}

# Corresponds to a video 
struct FrameContainer {
  id @0: UInt64;
  hd_video_filename: @1: Text;
  preview_video_filename: @2: Text;
  cam @2: Text;
  from @4 :Date;
  to @5 :Date;
  frames @ : List(Frame)
}
```
We would then have one capnproto file for each video. The map-reduce analysis could then operate on these files. 

As it is a very central issue which affects many people, we should discuss it in detail.

**Comment by walachey** [comment]
You are saying that the PostgreSQL database needs a lot of storage. Do not forget that databases are optimized for least overhead and maximum lookup time. If you start with a few billion single files containing e.g. capnproto serialization, you are basically rebuilding a database. Just with slower lookup and no indices.
Additionally, single files may have slight overhead (depending on the underlying filesystem) so that they will most likely take /more/ storage space instead of less (compared to a dedicated DB).

However, there are probably databases that are optimized for lookup (indices), storage space (least overhead) AND speed even though PostgreSQL might be bad at the latter.

Other than that, there are possibilities to cache the required input/output from and to the database in a very fast way and sync that later (I have used qless with a redis DB for a similar task - but there are probably a lot of possibilities).

**Comment by berleon** [comment]
I have my doubts that there exists any database that is capable of handling the
map-reduce/spark use-case well and still runs on a single server.
When doing map-reduce, the whole data is sent to multiple clients (probably 2-4).
Any database server would now have to read the full database, inevitable
becoming a bottleneck.
With many (capnproto) files, they are downloaded to the clients and deserialized there.
The only limiting factor here is the speed of the HDD. It might even fit onto
an SSD as the data should get smaller. I see no database that can compete with that in terms
of speed and simplicity.

The only index key we have is the time stamp. We can organize the directory structure
around the timestamp to ensure fast access times. Of course, we may need to tar
the capnproto files if they are too small.

What would be a use-case where it is beneficial to have the
detections in a database?

**Comment by timlandgraf** [comment]
I agree that we soon have to review the post-pipeline processing stages in the light of parallel processing architectures coming up. Franziska will present her thoughts on this matter on monday. So I guess we'll learn about technologies that work well with Spark.

**Comment by walachey** [comment]
>Any database server would now have to read the full database, inevitable
becoming a bottleneck.

I sure hope not database system has to read the full table from disk to access certain entries. Ideally it doesn't even have to read the full index.

>The only limiting factor here is the speed of the HDD

And the speed of the FS - because we still do the same things we would in a database (index by timestamp) just without a database. So we do the very same thing and just leave use the integrated database of the filesystem, which might or might not be optimized for our use case.
(Don't forget that a filesystem also has to figure out where exactly the file '/foo/bar/2016/03/05/1000_2000.baz' is stored, just like a database has to figure out where the entry is).

>What would be a use-case where it is beneficial to have the
detections in a database?

Fetching entries via some index (e.g. the timestamp). And then e.g. writing back metadata to the database. Most databases also have integrated failsafes that trigger e.g. if you are just saving a .capnproto file and the power goes off (and then the file is lost..?). Even better: most databases also have transactions! So if you are writing two .capnproto files and the second doesn't work (e.g. because someone has accidentally spawned two workers working on the same data, it would also not write the first file!)

But yeah, if we have only a small amount of data, no metadata and need no transactions and failsafes, we can as well use just the built-in FS. (We should choose a decent one, though).
And I obviously have no idea of spark and what works best with that :)

**Comment by berleon** [comment]
The output format will be Cap'N Proto. See this repository: https://github.com/BioroboticsLab/bb_binary
